spring:
  application:
    name: finalproject

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/wsb-final-project
    username: postgres
    password: 1234